<?php

declare(strict_types=1);

namespace ForumifyMilhqPluginMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260124143141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add MILHQ schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE milhq_after_action_report (report LONGTEXT NOT NULL, attendance JSON NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, unit_id INT DEFAULT NULL, mission_id INT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, INDEX IDX_2E6EEE498B8E8428 (created_at), INDEX IDX_2E6EEE4943625D9F (updated_at), INDEX IDX_2E6EEE49F8BD700D (unit_id), INDEX IDX_2E6EEE49BE6CAE90 (mission_id), INDEX IDX_2E6EEE49DE12AB56 (created_by), INDEX IDX_2E6EEE4916FE72E1 (updated_by), UNIQUE INDEX UNIQ_2E6EEE49BE6CAE90F8BD700D (mission_id, unit_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_award (name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_9FD23490462CE4F5 (position), INDEX IDX_9FD234908B8E8428 (created_at), INDEX IDX_9FD2349043625D9F (updated_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_course (title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, prerequisites LONGTEXT DEFAULT NULL, qualifications LONGTEXT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, position INT NOT NULL, minimum_rank_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_D8EA023C989D9B62 (slug), INDEX IDX_D8EA023C462CE4F5 (position), INDEX IDX_D8EA023C4BF66E9D (minimum_rank_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_course_class (title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, signup_from DATETIME NOT NULL, signup_until DATETIME NOT NULL, start DATETIME NOT NULL, end DATETIME NOT NULL, student_slots INT DEFAULT NULL, result TINYINT DEFAULT 0 NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, course_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, INDEX IDX_5453A4618B8E8428 (created_at), INDEX IDX_5453A46143625D9F (updated_at), INDEX IDX_5453A461591CC992 (course_id), INDEX IDX_5453A461DE12AB56 (created_by), INDEX IDX_5453A46116FE72E1 (updated_by), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_course_class_instructor (present TINYINT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, soldier_id INT DEFAULT NULL, class_id INT NOT NULL, instructor_id INT DEFAULT NULL, INDEX IDX_F9EDD079A38C1700 (soldier_id), INDEX IDX_F9EDD079EA000B10 (class_id), INDEX IDX_F9EDD0798C4FC193 (instructor_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_course_class_student (result VARCHAR(255) DEFAULT NULL, qualifications LONGTEXT DEFAULT NULL, service_record_text_override VARCHAR(255) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, soldier_id INT DEFAULT NULL, class_id INT NOT NULL, INDEX IDX_2B470A44A38C1700 (soldier_id), INDEX IDX_2B470A44EA000B10 (class_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_course_instructor (title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, course_id INT NOT NULL, INDEX IDX_ED2DC9F462CE4F5 (position), INDEX IDX_ED2DC9F591CC992 (course_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_document (name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, content LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, INDEX IDX_AD9E35E98B8E8428 (created_at), INDEX IDX_AD9E35E943625D9F (updated_at), INDEX IDX_AD9E35E9DE12AB56 (created_by), INDEX IDX_AD9E35E916FE72E1 (updated_by), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_form (name VARCHAR(255) NOT NULL, success_message LONGTEXT NOT NULL, description LONGTEXT NOT NULL, instructions LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, default_status_id INT DEFAULT NULL, INDEX IDX_1BFC3128B8E8428 (created_at), INDEX IDX_1BFC31243625D9F (updated_at), INDEX IDX_1BFC312FA95281A (default_status_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_form_field (`key` VARCHAR(255) NOT NULL, type VARCHAR(64) NOT NULL, label VARCHAR(255) NOT NULL, help LONGTEXT NOT NULL, required TINYINT NOT NULL, readonly TINYINT NOT NULL, options JSON DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, form_id INT DEFAULT NULL, INDEX IDX_75B5ACA4462CE4F5 (position), INDEX IDX_75B5ACA48B8E8428 (created_at), INDEX IDX_75B5ACA443625D9F (updated_at), INDEX IDX_75B5ACA45FF69B7D (form_id), UNIQUE INDEX UNIQ_75B5ACA45FF69B7DF48571EB (form_id, `key`), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_form_submission (data JSON DEFAULT NULL, status_reason LONGTEXT DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, form_id INT DEFAULT NULL, soldier_id INT DEFAULT NULL, status_id INT DEFAULT NULL, INDEX IDX_862B6DF18B8E8428 (created_at), INDEX IDX_862B6DF143625D9F (updated_at), INDEX IDX_862B6DF15FF69B7D (form_id), INDEX IDX_862B6DF1A38C1700 (soldier_id), INDEX IDX_862B6DF16BF700BD (status_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_mission (title VARCHAR(255) NOT NULL, briefing LONGTEXT NOT NULL, start DATETIME NOT NULL, end DATETIME DEFAULT NULL, send_notification TINYINT DEFAULT 0 NOT NULL, create_combat_records TINYINT DEFAULT 0 NOT NULL, combat_record_text VARCHAR(255) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, operation_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, UNIQUE INDEX UNIQ_D7BF1FE989D9B62 (slug), INDEX IDX_D7BF1FE8B8E8428 (created_at), INDEX IDX_D7BF1FE43625D9F (updated_at), INDEX IDX_D7BF1FE44AC3583 (operation_id), INDEX IDX_D7BF1FEDE12AB56 (created_by), INDEX IDX_D7BF1FE16FE72E1 (updated_by), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_mission_rsvp (going TINYINT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, soldier_id INT DEFAULT NULL, mission_id INT NOT NULL, INDEX IDX_E654D857A38C1700 (soldier_id), INDEX IDX_E654D857BE6CAE90 (mission_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_operation (title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, content LONGTEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, start DATE DEFAULT NULL, end DATE DEFAULT NULL, mission_briefing_template LONGTEXT NOT NULL, after_action_report_template LONGTEXT NOT NULL, request_rsvp TINYINT DEFAULT 0 NOT NULL, id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7944DF07989D9B62 (slug), INDEX IDX_7944DF078B8E8428 (created_at), INDEX IDX_7944DF0743625D9F (updated_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_position (name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, role_id INT DEFAULT NULL, INDEX IDX_33DB5B6A462CE4F5 (position), INDEX IDX_33DB5B6A8B8E8428 (created_at), INDEX IDX_33DB5B6A43625D9F (updated_at), INDEX IDX_33DB5B6AD60322AC (role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_qualification (name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_4396F625462CE4F5 (position), INDEX IDX_4396F6258B8E8428 (created_at), INDEX IDX_4396F62543625D9F (updated_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_rank (name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, abbreviation VARCHAR(8) NOT NULL, paygrade VARCHAR(16) NOT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_DB4ED6B8462CE4F5 (position), INDEX IDX_DB4ED6B88B8E8428 (created_at), INDEX IDX_DB4ED6B843625D9F (updated_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_record_assignment (type VARCHAR(16) NOT NULL, text LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, status_id INT DEFAULT NULL, unit_id INT DEFAULT NULL, position_id INT DEFAULT NULL, specialty_id INT DEFAULT NULL, soldier_id INT NOT NULL, author_id INT DEFAULT NULL, document_id INT DEFAULT NULL, INDEX IDX_9A4CA18A8B8E8428 (created_at), INDEX IDX_9A4CA18A43625D9F (updated_at), INDEX IDX_9A4CA18A6BF700BD (status_id), INDEX IDX_9A4CA18AF8BD700D (unit_id), INDEX IDX_9A4CA18ADD842E46 (position_id), INDEX IDX_9A4CA18A9A353316 (specialty_id), INDEX IDX_9A4CA18AA38C1700 (soldier_id), INDEX IDX_9A4CA18AF675F31B (author_id), INDEX IDX_9A4CA18AC33F7837 (document_id), INDEX IDX_9A4CA18A8CDE5729 (type), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_record_award (text LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, soldier_id INT NOT NULL, award_id INT DEFAULT NULL, author_id INT DEFAULT NULL, document_id INT DEFAULT NULL, INDEX IDX_5BB335AD8B8E8428 (created_at), INDEX IDX_5BB335AD43625D9F (updated_at), INDEX IDX_5BB335ADA38C1700 (soldier_id), INDEX IDX_5BB335AD3D5282CF (award_id), INDEX IDX_5BB335ADF675F31B (author_id), INDEX IDX_5BB335ADC33F7837 (document_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_record_combat (text LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, soldier_id INT NOT NULL, author_id INT DEFAULT NULL, document_id INT DEFAULT NULL, INDEX IDX_1B89A30D8B8E8428 (created_at), INDEX IDX_1B89A30D43625D9F (updated_at), INDEX IDX_1B89A30DA38C1700 (soldier_id), INDEX IDX_1B89A30DF675F31B (author_id), INDEX IDX_1B89A30DC33F7837 (document_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_record_qualification (text LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, soldier_id INT NOT NULL, qualification_id INT DEFAULT NULL, author_id INT DEFAULT NULL, document_id INT DEFAULT NULL, INDEX IDX_241429D98B8E8428 (created_at), INDEX IDX_241429D943625D9F (updated_at), INDEX IDX_241429D9A38C1700 (soldier_id), INDEX IDX_241429D91A75EE38 (qualification_id), INDEX IDX_241429D9F675F31B (author_id), INDEX IDX_241429D9C33F7837 (document_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_record_rank (type VARCHAR(16) NOT NULL, text LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, soldier_id INT NOT NULL, rank_id INT DEFAULT NULL, author_id INT DEFAULT NULL, document_id INT DEFAULT NULL, INDEX IDX_DB0553418B8E8428 (created_at), INDEX IDX_DB05534143625D9F (updated_at), INDEX IDX_DB055341A38C1700 (soldier_id), INDEX IDX_DB0553417616678F (rank_id), INDEX IDX_DB055341F675F31B (author_id), INDEX IDX_DB055341C33F7837 (document_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_record_service (text LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, soldier_id INT NOT NULL, author_id INT DEFAULT NULL, document_id INT DEFAULT NULL, INDEX IDX_616E25598B8E8428 (created_at), INDEX IDX_616E255943625D9F (updated_at), INDEX IDX_616E2559A38C1700 (soldier_id), INDEX IDX_616E2559F675F31B (author_id), INDEX IDX_616E2559C33F7837 (document_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_report_in (last_report_in_date DATETIME NOT NULL, id INT AUTO_INCREMENT NOT NULL, soldier_id INT DEFAULT NULL, return_status_id INT DEFAULT NULL, INDEX IDX_CBC234B4A38C1700 (soldier_id), INDEX IDX_CBC234B49EEEBE0D (return_status_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_roster (name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_AECDC07C462CE4F5 (position), INDEX IDX_AECDC07C8B8E8428 (created_at), INDEX IDX_AECDC07C43625D9F (updated_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_roster_units (roster_id INT NOT NULL, unit_id INT NOT NULL, INDEX IDX_A1BCFB0575404483 (roster_id), INDEX IDX_A1BCFB05F8BD700D (unit_id), PRIMARY KEY (roster_id, unit_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_soldier (name VARCHAR(255) NOT NULL, signature VARCHAR(255) DEFAULT NULL, uniform VARCHAR(255) DEFAULT NULL, steam_id BIGINT UNSIGNED DEFAULT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, user_id INT DEFAULT NULL, rank_id INT DEFAULT NULL, unit_id INT DEFAULT NULL, position_id INT DEFAULT NULL, specialty_id INT DEFAULT NULL, status_id INT DEFAULT NULL, enlistment_topic_id INT DEFAULT NULL, INDEX IDX_2D532EC08B8E8428 (created_at), INDEX IDX_2D532EC043625D9F (updated_at), UNIQUE INDEX UNIQ_2D532EC0A76ED395 (user_id), INDEX IDX_2D532EC07616678F (rank_id), INDEX IDX_2D532EC0F8BD700D (unit_id), INDEX IDX_2D532EC0DD842E46 (position_id), INDEX IDX_2D532EC09A353316 (specialty_id), INDEX IDX_2D532EC06BF700BD (status_id), UNIQUE INDEX UNIQ_2D532EC0447F7CAA (enlistment_topic_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_specialty (name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, abbreviation VARCHAR(8) NOT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, role_id INT DEFAULT NULL, INDEX IDX_80A3DF86462CE4F5 (position), INDEX IDX_80A3DF868B8E8428 (created_at), INDEX IDX_80A3DF8643625D9F (updated_at), INDEX IDX_80A3DF86D60322AC (role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_status (name VARCHAR(255) NOT NULL, color CHAR(7) NOT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, role_id INT DEFAULT NULL, INDEX IDX_B5740899462CE4F5 (position), INDEX IDX_B57408998B8E8428 (created_at), INDEX IDX_B574089943625D9F (updated_at), INDEX IDX_B5740899D60322AC (role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_unit (name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, mark_supervisors_on_roster TINYINT DEFAULT 1 NOT NULL, id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, role_id INT DEFAULT NULL, INDEX IDX_8F8C320E462CE4F5 (position), INDEX IDX_8F8C320E8B8E8428 (created_at), INDEX IDX_8F8C320E43625D9F (updated_at), INDEX IDX_8F8C320ED60322AC (role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE milhq_unit_supervisors (unit_id INT NOT NULL, position_id INT NOT NULL, INDEX IDX_2A7A919BF8BD700D (unit_id), INDEX IDX_2A7A919BDD842E46 (position_id), PRIMARY KEY (unit_id, position_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE milhq_after_action_report ADD CONSTRAINT FK_2E6EEE49F8BD700D FOREIGN KEY (unit_id) REFERENCES milhq_unit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_after_action_report ADD CONSTRAINT FK_2E6EEE49BE6CAE90 FOREIGN KEY (mission_id) REFERENCES milhq_mission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_after_action_report ADD CONSTRAINT FK_2E6EEE49DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_after_action_report ADD CONSTRAINT FK_2E6EEE4916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_course ADD CONSTRAINT FK_D8EA023C4BF66E9D FOREIGN KEY (minimum_rank_id) REFERENCES milhq_rank (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_course_class ADD CONSTRAINT FK_5453A461591CC992 FOREIGN KEY (course_id) REFERENCES milhq_course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_course_class ADD CONSTRAINT FK_5453A461DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_course_class ADD CONSTRAINT FK_5453A46116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_course_class_instructor ADD CONSTRAINT FK_F9EDD079A38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_course_class_instructor ADD CONSTRAINT FK_F9EDD079EA000B10 FOREIGN KEY (class_id) REFERENCES milhq_course_class (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_course_class_instructor ADD CONSTRAINT FK_F9EDD0798C4FC193 FOREIGN KEY (instructor_id) REFERENCES milhq_course_instructor (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_course_class_student ADD CONSTRAINT FK_2B470A44A38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_course_class_student ADD CONSTRAINT FK_2B470A44EA000B10 FOREIGN KEY (class_id) REFERENCES milhq_course_class (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_course_instructor ADD CONSTRAINT FK_ED2DC9F591CC992 FOREIGN KEY (course_id) REFERENCES milhq_course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_document ADD CONSTRAINT FK_AD9E35E9DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_document ADD CONSTRAINT FK_AD9E35E916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_form ADD CONSTRAINT FK_1BFC312FA95281A FOREIGN KEY (default_status_id) REFERENCES milhq_status (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_form_field ADD CONSTRAINT FK_75B5ACA45FF69B7D FOREIGN KEY (form_id) REFERENCES milhq_form (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_form_submission ADD CONSTRAINT FK_862B6DF15FF69B7D FOREIGN KEY (form_id) REFERENCES milhq_form (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_form_submission ADD CONSTRAINT FK_862B6DF1A38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_form_submission ADD CONSTRAINT FK_862B6DF16BF700BD FOREIGN KEY (status_id) REFERENCES milhq_status (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_mission ADD CONSTRAINT FK_D7BF1FE44AC3583 FOREIGN KEY (operation_id) REFERENCES milhq_operation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_mission ADD CONSTRAINT FK_D7BF1FEDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_mission ADD CONSTRAINT FK_D7BF1FE16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_mission_rsvp ADD CONSTRAINT FK_E654D857A38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_mission_rsvp ADD CONSTRAINT FK_E654D857BE6CAE90 FOREIGN KEY (mission_id) REFERENCES milhq_mission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_position ADD CONSTRAINT FK_33DB5B6AD60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_assignment ADD CONSTRAINT FK_9A4CA18A6BF700BD FOREIGN KEY (status_id) REFERENCES milhq_status (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_assignment ADD CONSTRAINT FK_9A4CA18AF8BD700D FOREIGN KEY (unit_id) REFERENCES milhq_unit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_assignment ADD CONSTRAINT FK_9A4CA18ADD842E46 FOREIGN KEY (position_id) REFERENCES milhq_position (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_assignment ADD CONSTRAINT FK_9A4CA18A9A353316 FOREIGN KEY (specialty_id) REFERENCES milhq_specialty (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_assignment ADD CONSTRAINT FK_9A4CA18AA38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_assignment ADD CONSTRAINT FK_9A4CA18AF675F31B FOREIGN KEY (author_id) REFERENCES milhq_soldier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_assignment ADD CONSTRAINT FK_9A4CA18AC33F7837 FOREIGN KEY (document_id) REFERENCES milhq_document (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_award ADD CONSTRAINT FK_5BB335ADA38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_award ADD CONSTRAINT FK_5BB335AD3D5282CF FOREIGN KEY (award_id) REFERENCES milhq_award (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_award ADD CONSTRAINT FK_5BB335ADF675F31B FOREIGN KEY (author_id) REFERENCES milhq_soldier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_award ADD CONSTRAINT FK_5BB335ADC33F7837 FOREIGN KEY (document_id) REFERENCES milhq_document (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_combat ADD CONSTRAINT FK_1B89A30DA38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_combat ADD CONSTRAINT FK_1B89A30DF675F31B FOREIGN KEY (author_id) REFERENCES milhq_soldier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_combat ADD CONSTRAINT FK_1B89A30DC33F7837 FOREIGN KEY (document_id) REFERENCES milhq_document (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_qualification ADD CONSTRAINT FK_241429D9A38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_qualification ADD CONSTRAINT FK_241429D91A75EE38 FOREIGN KEY (qualification_id) REFERENCES milhq_qualification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_qualification ADD CONSTRAINT FK_241429D9F675F31B FOREIGN KEY (author_id) REFERENCES milhq_soldier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_qualification ADD CONSTRAINT FK_241429D9C33F7837 FOREIGN KEY (document_id) REFERENCES milhq_document (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_rank ADD CONSTRAINT FK_DB055341A38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_rank ADD CONSTRAINT FK_DB0553417616678F FOREIGN KEY (rank_id) REFERENCES milhq_rank (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_rank ADD CONSTRAINT FK_DB055341F675F31B FOREIGN KEY (author_id) REFERENCES milhq_soldier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_rank ADD CONSTRAINT FK_DB055341C33F7837 FOREIGN KEY (document_id) REFERENCES milhq_document (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_service ADD CONSTRAINT FK_616E2559A38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_record_service ADD CONSTRAINT FK_616E2559F675F31B FOREIGN KEY (author_id) REFERENCES milhq_soldier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_record_service ADD CONSTRAINT FK_616E2559C33F7837 FOREIGN KEY (document_id) REFERENCES milhq_document (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_report_in ADD CONSTRAINT FK_CBC234B4A38C1700 FOREIGN KEY (soldier_id) REFERENCES milhq_soldier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_report_in ADD CONSTRAINT FK_CBC234B49EEEBE0D FOREIGN KEY (return_status_id) REFERENCES milhq_status (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_roster_units ADD CONSTRAINT FK_A1BCFB0575404483 FOREIGN KEY (roster_id) REFERENCES milhq_roster (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_roster_units ADD CONSTRAINT FK_A1BCFB05F8BD700D FOREIGN KEY (unit_id) REFERENCES milhq_unit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_soldier ADD CONSTRAINT FK_2D532EC0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_soldier ADD CONSTRAINT FK_2D532EC07616678F FOREIGN KEY (rank_id) REFERENCES milhq_rank (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_soldier ADD CONSTRAINT FK_2D532EC0F8BD700D FOREIGN KEY (unit_id) REFERENCES milhq_unit (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_soldier ADD CONSTRAINT FK_2D532EC0DD842E46 FOREIGN KEY (position_id) REFERENCES milhq_position (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_soldier ADD CONSTRAINT FK_2D532EC09A353316 FOREIGN KEY (specialty_id) REFERENCES milhq_specialty (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_soldier ADD CONSTRAINT FK_2D532EC06BF700BD FOREIGN KEY (status_id) REFERENCES milhq_status (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_soldier ADD CONSTRAINT FK_2D532EC0447F7CAA FOREIGN KEY (enlistment_topic_id) REFERENCES topic (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_specialty ADD CONSTRAINT FK_80A3DF86D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_status ADD CONSTRAINT FK_B5740899D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_unit ADD CONSTRAINT FK_8F8C320ED60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE milhq_unit_supervisors ADD CONSTRAINT FK_2A7A919BF8BD700D FOREIGN KEY (unit_id) REFERENCES milhq_unit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE milhq_unit_supervisors ADD CONSTRAINT FK_2A7A919BDD842E46 FOREIGN KEY (position_id) REFERENCES milhq_position (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE milhq_after_action_report DROP FOREIGN KEY FK_2E6EEE49F8BD700D');
        $this->addSql('ALTER TABLE milhq_after_action_report DROP FOREIGN KEY FK_2E6EEE49BE6CAE90');
        $this->addSql('ALTER TABLE milhq_after_action_report DROP FOREIGN KEY FK_2E6EEE49DE12AB56');
        $this->addSql('ALTER TABLE milhq_after_action_report DROP FOREIGN KEY FK_2E6EEE4916FE72E1');
        $this->addSql('ALTER TABLE milhq_course DROP FOREIGN KEY FK_D8EA023C4BF66E9D');
        $this->addSql('ALTER TABLE milhq_course_class DROP FOREIGN KEY FK_5453A461591CC992');
        $this->addSql('ALTER TABLE milhq_course_class DROP FOREIGN KEY FK_5453A461DE12AB56');
        $this->addSql('ALTER TABLE milhq_course_class DROP FOREIGN KEY FK_5453A46116FE72E1');
        $this->addSql('ALTER TABLE milhq_course_class_instructor DROP FOREIGN KEY FK_F9EDD079A38C1700');
        $this->addSql('ALTER TABLE milhq_course_class_instructor DROP FOREIGN KEY FK_F9EDD079EA000B10');
        $this->addSql('ALTER TABLE milhq_course_class_instructor DROP FOREIGN KEY FK_F9EDD0798C4FC193');
        $this->addSql('ALTER TABLE milhq_course_class_student DROP FOREIGN KEY FK_2B470A44A38C1700');
        $this->addSql('ALTER TABLE milhq_course_class_student DROP FOREIGN KEY FK_2B470A44EA000B10');
        $this->addSql('ALTER TABLE milhq_course_instructor DROP FOREIGN KEY FK_ED2DC9F591CC992');
        $this->addSql('ALTER TABLE milhq_document DROP FOREIGN KEY FK_AD9E35E9DE12AB56');
        $this->addSql('ALTER TABLE milhq_document DROP FOREIGN KEY FK_AD9E35E916FE72E1');
        $this->addSql('ALTER TABLE milhq_form DROP FOREIGN KEY FK_1BFC312FA95281A');
        $this->addSql('ALTER TABLE milhq_form_field DROP FOREIGN KEY FK_75B5ACA45FF69B7D');
        $this->addSql('ALTER TABLE milhq_form_submission DROP FOREIGN KEY FK_862B6DF15FF69B7D');
        $this->addSql('ALTER TABLE milhq_form_submission DROP FOREIGN KEY FK_862B6DF1A38C1700');
        $this->addSql('ALTER TABLE milhq_form_submission DROP FOREIGN KEY FK_862B6DF16BF700BD');
        $this->addSql('ALTER TABLE milhq_mission DROP FOREIGN KEY FK_D7BF1FE44AC3583');
        $this->addSql('ALTER TABLE milhq_mission DROP FOREIGN KEY FK_D7BF1FEDE12AB56');
        $this->addSql('ALTER TABLE milhq_mission DROP FOREIGN KEY FK_D7BF1FE16FE72E1');
        $this->addSql('ALTER TABLE milhq_mission_rsvp DROP FOREIGN KEY FK_E654D857A38C1700');
        $this->addSql('ALTER TABLE milhq_mission_rsvp DROP FOREIGN KEY FK_E654D857BE6CAE90');
        $this->addSql('ALTER TABLE milhq_position DROP FOREIGN KEY FK_33DB5B6AD60322AC');
        $this->addSql('ALTER TABLE milhq_record_assignment DROP FOREIGN KEY FK_9A4CA18A6BF700BD');
        $this->addSql('ALTER TABLE milhq_record_assignment DROP FOREIGN KEY FK_9A4CA18AF8BD700D');
        $this->addSql('ALTER TABLE milhq_record_assignment DROP FOREIGN KEY FK_9A4CA18ADD842E46');
        $this->addSql('ALTER TABLE milhq_record_assignment DROP FOREIGN KEY FK_9A4CA18A9A353316');
        $this->addSql('ALTER TABLE milhq_record_assignment DROP FOREIGN KEY FK_9A4CA18AA38C1700');
        $this->addSql('ALTER TABLE milhq_record_assignment DROP FOREIGN KEY FK_9A4CA18AF675F31B');
        $this->addSql('ALTER TABLE milhq_record_assignment DROP FOREIGN KEY FK_9A4CA18AC33F7837');
        $this->addSql('ALTER TABLE milhq_record_award DROP FOREIGN KEY FK_5BB335ADA38C1700');
        $this->addSql('ALTER TABLE milhq_record_award DROP FOREIGN KEY FK_5BB335AD3D5282CF');
        $this->addSql('ALTER TABLE milhq_record_award DROP FOREIGN KEY FK_5BB335ADF675F31B');
        $this->addSql('ALTER TABLE milhq_record_award DROP FOREIGN KEY FK_5BB335ADC33F7837');
        $this->addSql('ALTER TABLE milhq_record_combat DROP FOREIGN KEY FK_1B89A30DA38C1700');
        $this->addSql('ALTER TABLE milhq_record_combat DROP FOREIGN KEY FK_1B89A30DF675F31B');
        $this->addSql('ALTER TABLE milhq_record_combat DROP FOREIGN KEY FK_1B89A30DC33F7837');
        $this->addSql('ALTER TABLE milhq_record_qualification DROP FOREIGN KEY FK_241429D9A38C1700');
        $this->addSql('ALTER TABLE milhq_record_qualification DROP FOREIGN KEY FK_241429D91A75EE38');
        $this->addSql('ALTER TABLE milhq_record_qualification DROP FOREIGN KEY FK_241429D9F675F31B');
        $this->addSql('ALTER TABLE milhq_record_qualification DROP FOREIGN KEY FK_241429D9C33F7837');
        $this->addSql('ALTER TABLE milhq_record_rank DROP FOREIGN KEY FK_DB055341A38C1700');
        $this->addSql('ALTER TABLE milhq_record_rank DROP FOREIGN KEY FK_DB0553417616678F');
        $this->addSql('ALTER TABLE milhq_record_rank DROP FOREIGN KEY FK_DB055341F675F31B');
        $this->addSql('ALTER TABLE milhq_record_rank DROP FOREIGN KEY FK_DB055341C33F7837');
        $this->addSql('ALTER TABLE milhq_record_service DROP FOREIGN KEY FK_616E2559A38C1700');
        $this->addSql('ALTER TABLE milhq_record_service DROP FOREIGN KEY FK_616E2559F675F31B');
        $this->addSql('ALTER TABLE milhq_record_service DROP FOREIGN KEY FK_616E2559C33F7837');
        $this->addSql('ALTER TABLE milhq_report_in DROP FOREIGN KEY FK_CBC234B4A38C1700');
        $this->addSql('ALTER TABLE milhq_report_in DROP FOREIGN KEY FK_CBC234B49EEEBE0D');
        $this->addSql('ALTER TABLE milhq_roster_units DROP FOREIGN KEY FK_A1BCFB0575404483');
        $this->addSql('ALTER TABLE milhq_roster_units DROP FOREIGN KEY FK_A1BCFB05F8BD700D');
        $this->addSql('ALTER TABLE milhq_soldier DROP FOREIGN KEY FK_2D532EC0A76ED395');
        $this->addSql('ALTER TABLE milhq_soldier DROP FOREIGN KEY FK_2D532EC07616678F');
        $this->addSql('ALTER TABLE milhq_soldier DROP FOREIGN KEY FK_2D532EC0F8BD700D');
        $this->addSql('ALTER TABLE milhq_soldier DROP FOREIGN KEY FK_2D532EC0DD842E46');
        $this->addSql('ALTER TABLE milhq_soldier DROP FOREIGN KEY FK_2D532EC09A353316');
        $this->addSql('ALTER TABLE milhq_soldier DROP FOREIGN KEY FK_2D532EC06BF700BD');
        $this->addSql('ALTER TABLE milhq_soldier DROP FOREIGN KEY FK_2D532EC0447F7CAA');
        $this->addSql('ALTER TABLE milhq_specialty DROP FOREIGN KEY FK_80A3DF86D60322AC');
        $this->addSql('ALTER TABLE milhq_status DROP FOREIGN KEY FK_B5740899D60322AC');
        $this->addSql('ALTER TABLE milhq_unit DROP FOREIGN KEY FK_8F8C320ED60322AC');
        $this->addSql('ALTER TABLE milhq_unit_supervisors DROP FOREIGN KEY FK_2A7A919BF8BD700D');
        $this->addSql('ALTER TABLE milhq_unit_supervisors DROP FOREIGN KEY FK_2A7A919BDD842E46');
        $this->addSql('DROP TABLE milhq_after_action_report');
        $this->addSql('DROP TABLE milhq_award');
        $this->addSql('DROP TABLE milhq_course');
        $this->addSql('DROP TABLE milhq_course_class');
        $this->addSql('DROP TABLE milhq_course_class_instructor');
        $this->addSql('DROP TABLE milhq_course_class_student');
        $this->addSql('DROP TABLE milhq_course_instructor');
        $this->addSql('DROP TABLE milhq_document');
        $this->addSql('DROP TABLE milhq_form');
        $this->addSql('DROP TABLE milhq_form_field');
        $this->addSql('DROP TABLE milhq_form_submission');
        $this->addSql('DROP TABLE milhq_mission');
        $this->addSql('DROP TABLE milhq_mission_rsvp');
        $this->addSql('DROP TABLE milhq_operation');
        $this->addSql('DROP TABLE milhq_position');
        $this->addSql('DROP TABLE milhq_qualification');
        $this->addSql('DROP TABLE milhq_rank');
        $this->addSql('DROP TABLE milhq_record_assignment');
        $this->addSql('DROP TABLE milhq_record_award');
        $this->addSql('DROP TABLE milhq_record_combat');
        $this->addSql('DROP TABLE milhq_record_qualification');
        $this->addSql('DROP TABLE milhq_record_rank');
        $this->addSql('DROP TABLE milhq_record_service');
        $this->addSql('DROP TABLE milhq_report_in');
        $this->addSql('DROP TABLE milhq_roster');
        $this->addSql('DROP TABLE milhq_roster_units');
        $this->addSql('DROP TABLE milhq_soldier');
        $this->addSql('DROP TABLE milhq_specialty');
        $this->addSql('DROP TABLE milhq_status');
        $this->addSql('DROP TABLE milhq_unit');
        $this->addSql('DROP TABLE milhq_unit_supervisors');
    }
}
