name: Set up forumify
description: Prepares forumify as an application to run tests

inputs:
    additional-plugin:
        required: false
        default: ''

runs:
    using: composite
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: '8.4'
              tools: composer
              extensions: mbstring, xml, ctype, iconv, intl, mysql

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup forumify
          shell: bash
          run: |
              if [ -n "${{ inputs.additional-plugin }}" ]; then
                composer require ${{ inputs.additional-plugin }} --no-update
              fi
              composer install --no-progress
              cd tests
              php bin/console doctrine:database:create --env=test
              php bin/console doctrine:migrations:migrate --no-interaction --env=test
              php bin/console forumify:platform:setting -k forumify.platform_installed --value true
              php bin/console forumify:plugins:refresh --env=test
              php bin/console forumify:plugins:activate forumify/forumify-milhq-plugin --env=test
              if [ -n "${{ inputs.additional-plugin }}" ]; then
                php bin/console forumify:plugins:activate ${{ inputs.additional-plugin }} --env=test
              fi
