name: Set up forumify
description: Prepares forumify as an application to run tests

inputs:
    plugin:
        required: false
        default: ''
    plugin-version:
        required: false
        default: '*'


runs:
    using: composite
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: '8.4'
              tools: composer
              extensions: mbstring, xml, ctype, iconv, intl, mysql

        - name: Install dependencies
          shell: bash
          run: composer install --no-progress

        - name: Install plugin
          if: ${{ inputs.plugin }}
          shell: bash
          run: composer require "${{ inputs.plugin }}:${{ inputs.plugin-version }}"

        - name: Start forumify test
          shell: bash
          working-directory: tests
          run: php bin/console forumify:plugins:test-setup --env=test

        - name: Enable additional plugin
          if: ${{ inputs.plugin }}
          shell: bash
          working-directory: tests
          run: php bin/console forumify:plugins:activate ${{ inputs.plugin }} --env=test
