name: Code Quality
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Setup JS
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Checkout code
        uses: actions/checkout@v6

      - parallel:
        - name: Install PHP Dependencies
          run: |
            composer require --no-update \
              "forumify/forumify-calendar-plugin:^1.1" \
              "forumify/forumify-discord-plugin:^1.1"
            composer install --no-progress

        - name: Install JS Dependencies
          working-directory: assets
          run: npm install --force

      - name: Run PHP checks
        run: |
          ./vendor/bin/phpcs -s --standard=phpcs.xml
          ./vendor/bin/phpstan analyze -v

      - name: Run JS checks
        working-directory: assets
        run: npm run lint
