name: Automated Tests
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Start test env
        uses: ./.github/workflows/setup-env

      - name: Run tests
        run: vendor/bin/phpunit

  tests-calendar:
    name: Run Tests (With Calendar)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Start test env
        uses: ./.github/workflows/setup-env
        with:
          additional-plugin: forumify/forumify-calendar-plugin

      - name: Run tests
        run: vendor/bin/phpunit

  tests-discord:
    name: Run Tests (With Discord)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Start test env
        uses: ./.github/workflows/setup-env
        with:
          additional-plugin: forumify/forumify-discord-plugin

      - name: Run tests
        run: vendor/bin/phpunit
